### ISSUE TITLE
esp32 esp-at ImportError: cannot import name 'PREVIEW_TARGETS'

### ISSUE THREAD

**Issue by zgzd0222** [espressif/esp-at#580]
----------------------------- Delete below -----------------------------

If your issue is a general question, starts similar to "How do I..", or is related to 3rd party development kits/libs, please discuss this on our community forum at esp32.com instead.

INSTRUCTIONS
============

Before submitting a new issue, please follow the checklist and try to find the answer.

- [x] I have read the documentation [ESP-IDF Programming Guide](https://docs.espressif.com/projects/esp-idf/en/latest/) and the issue is not addressed there.
- [ ] I have updated my IDF branch (master or release) to the latest version and checked that the issue is present there.
- [ ] I have searched the issue tracker for a similar issue and not found a similar issue.

If the issue cannot be solved after the steps before, please follow these instructions so we can get the needed information to help you in a quick and effective fashion.

1. Fill in all the fields under **Environment** marked with [ ] by picking the correct option for you in each case and deleting the others.
2. Describe your problem.
3. Include [debug logs on the monitor](https://docs.espressif.com/projects/esp-idf/en/latest/get-started/idf-monitor.html#automatically-decoding-addresses) or the [coredump](https://docs.espressif.com/projects/esp-idf/en/latest/api-guides/core_dump.html).
4. Provide more items under **Other items if possible** can help us better locate your problem.
5. Use markup (buttons above) and the Preview tab to check what the issue will look like.
6. Delete these instructions from the above to the below marker lines before submitting this issue.

----------------------------- Delete above -----------------------------

## Environment

- Development Kit:     ESP32-DevKitC
- Kit version DevKitC
- Module or chip used:  [ESP32-WROOM-32
- IDF version (run ``git describe --tags`` to find it): 
    // v2.2.0.0_esp32c3-170-g283d237
- Build System:         [Make|CMake]
- Compiler version (run ``xtensa-esp32-elf-gcc --version`` to find it):
    // xtensa-esp32-elf-gcc (crosstool-NG esp-2021r1) 8.4.0
- Operating System:    Linux
- Power Supply:         USB

## Problem Description

//Detailed problem description goes here.
when use the command: ./build.py menuconfig, the log as below:
from idf_py_actions.constants import GENERATORS, PREVIEW_TARGETS, SUPPORTED_TARGETS, URL_TO_DOC
ImportError: cannot import name 'PREVIEW_TARGETS'
idf.py build ret: 1
idf.py build failed

**Comment by ustccw** [comment]
@zgzd0222 please provide all logs after you cloned esp-at project.

**Comment by FBEZ** [comment]
I have a similar issue, but I get 

from idf_py_actions.constants import GENERATORS, PREVIEW_TARGETS, SUPPORTED_TARGETS, URL_TO_DOC
ImportError: cannot import name 'URL_TO_DOC' from 'idf_py_actions.constants' (C:\Users\Francesco\esp\esp-at\esp-idf\tools\idf_py_actions\constants.py)

## Log after cloning esp-at

C:\Users\Francesco\esp>git clone --recursive https://github.com/espressif/esp-at.git
Cloning into 'esp-at'...
remote: Enumerating objects: 12176, done.
remote: Counting objects: 100% (3950/3950), done.
remote: Compressing objects: 100% (1976/1976), done.
remote: Total 12176 (delta 2832), reused 2993 (delta 1932), pack-reused 8226 eceiving objects: 100% (12176/12176), 109.24 MiB | 8.93 MiB/s
Receiving objects: 100% (12176/12176), 111.74 MiB | 6.75 MiB/s, done.
Resolving deltas: 100% (7479/7479), done.

C:\Users\Francesco\esp>cd esp-at

C:\Users\Francesco\esp\esp-at>build.py menuconfig
Traceback (most recent call last):
  File "C:\Users\Francesco\esp\esp-at\build.py", line 25, in <module>
    import xlrd
ModuleNotFoundError: No module named 'xlrd'

C:\Users\Francesco\esp\esp-at>python -m pip install pyyaml xlrd
Requirement already satisfied: pyyaml in c:\espressif\python_env\idf4.4_py3.8_env\lib\site-packages (6.0)
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
     |████████████████████████████████| 96 kB 1.6 MB/s
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1
WARNING: You are using pip version 20.3.3; however, version 22.0.3 is available.
You should consider upgrading via the 'C:\Espressif\python_env\idf4.4_py3.8_env\Scripts\python.exe -m pip install --upgrade pip' command.

C:\Users\Francesco\esp\esp-at>build.py menuconfig
Platform name:
1. PLATFORM_ESP32
2. PLATFORM_ESP32C3
choose(range[1,2]):2

Module name:
1. MINI-1 (description: TX:7 RX:6)
2. ESP32C3-SPI
3. ESP32C3_QCLOUD (description: QCLOUD TX:7 RX:6)
choose(range[1,3]):1

Enable silence mode to remove some logs and reduce the firmware size?
0. No
1. Yes
choose(range[0,1]):0
platform_name=ESP32C3,module_name=MINI-1
Please wait for the SDK download to finish...
Cloning into 'esp-idf'...
remote: Enumerating objects: 309424, done.
remote: Counting objects: 100% (192/192), done.
remote: Compressing objects: 100% (105/105), done.
remote: Total 309424 (delta 84), reused 188 (delta 80), pack-reused 309232
Receiving objects: 100% (309424/309424), 174.29 MiB | 6.22 MiB/s, done.
Resolving deltas: 100% (228786/228786), done.
Updating files: 100% (8422/8422), done.
old commit:c831d1f1e00891ab6b69db48b7889a19437ec237
checkout commit:87f8a0d5f11fea174f8a77bf230bb9caf6caf38e
Please wait for the update to complete, which will take some time
Already up to date.
Note: switching to '87f8a0d5f11fea174f8a77bf230bb9caf6caf38e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 87f8a0d5f1 Merge branch 'bugfix/efuse_timesettigs_in_burn_op_v4.3' into 'release/v4.3'
Submodule 'components/asio/asio' (https://github.com/espressif/asio.git) registered for path 'components/asio/asio'
Submodule 'components/bootloader/subproject/components/micro-ecc/micro-ecc' (https://github.com/kmackay/micro-ecc.git) registered for path 'components/bootloader/subproject/components/micro-ecc/micro-ecc'
Submodule 'components/bt/controller/lib_esp32' (https://github.com/espressif/esp32-bt-lib.git) registered for path 'components/bt/controller/lib_esp32'
Submodule 'components/bt/controller/lib_esp32c3_family' (https://github.com/espressif/esp32c3-bt-lib.git) registered for path 'components/bt/controller/lib_esp32c3_family'
Submodule 'components/bt/host/nimble/nimble' (https://github.com/espressif/esp-nimble.git) registered for path 'components/bt/host/nimble/nimble'
Submodule 'components/cbor/tinycbor' (https://github.com/intel/tinycbor.git) registered for path 'components/cbor/tinycbor'
Submodule 'components/cmock/CMock' (https://github.com/ThrowTheSwitch/CMock.git) registered for path 'components/cmock/CMock'
Submodule 'components/coap/libcoap' (https://github.com/obgm/libcoap.git) registered for path 'components/coap/libcoap'
Submodule 'components/esp_wifi/lib' (https://github.com/espressif/esp32-wifi-lib.git) registered for path 'components/esp_wifi/lib'
Submodule 'components/esptool_py/esptool' (https://github.com/espressif/esptool.git) registered for path 'components/esptool_py/esptool'
Submodule 'components/expat/expat' (https://github.com/libexpat/libexpat.git) registered for path 'components/expat/expat'
Submodule 'components/json/cJSON' (https://github.com/DaveGamble/cJSON.git) registered for path 'components/json/cJSON'
Submodule 'components/libsodium/libsodium' (https://github.com/jedisct1/libsodium.git) registered for path 'components/libsodium/libsodium'
Submodule 'components/lwip/lwip' (https://github.com/espressif/esp-lwip.git) registered for path 'components/lwip/lwip'
Submodule 'components/mbedtls/mbedtls' (https://github.com/espressif/mbedtls.git) registered for path 'components/mbedtls/mbedtls'
Submodule 'components/mqtt/esp-mqtt' (https://github.com/espressif/esp-mqtt.git) registered for path 'components/mqtt/esp-mqtt'
Submodule 'components/nghttp/nghttp2' (https://github.com/nghttp2/nghttp2.git) registered for path 'components/nghttp/nghttp2'
Submodule 'components/protobuf-c/protobuf-c' (https://github.com/protobuf-c/protobuf-c.git) registered for path 'components/protobuf-c/protobuf-c'
Submodule 'components/spiffs/spiffs' (https://github.com/pellepl/spiffs.git) registered for path 'components/spiffs/spiffs'
Submodule 'components/tinyusb/tinyusb' (https://github.com/espressif/tinyusb.git) registered for path 'components/tinyusb/tinyusb'
Submodule 'components/unity/unity' (https://github.com/ThrowTheSwitch/Unity.git) registered for path 'components/unity/unity'
Submodule 'examples/build_system/cmake/import_lib/main/lib/tinyxml2' (https://github.com/leethomason/tinyxml2.git) registered for path 'examples/build_system/cmake/import_lib/main/lib/tinyxml2'
Submodule 'examples/peripherals/secure_element/atecc608_ecdsa/components/esp-cryptoauthlib' (https://github.com/espressif/esp-cryptoauthlib.git) registered for path 'examples/peripherals/secure_element/atecc608_ecdsa/components/esp-cryptoauthlib'
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/asio/asio'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/bootloader/subproject/components/micro-ecc/micro-ecc'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/bt/controller/lib_esp32'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/bt/controller/lib_esp32c3_family'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/bt/host/nimble/nimble'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/cbor/tinycbor'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/cmock/CMock'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/coap/libcoap'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/esp_wifi/lib'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/esptool_py/esptool'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/expat/expat'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/json/cJSON'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/libsodium/libsodium'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/lwip/lwip'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/mbedtls/mbedtls'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/mqtt/esp-mqtt'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/nghttp/nghttp2'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/protobuf-c/protobuf-c'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/spiffs/spiffs'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/tinyusb/tinyusb'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/unity/unity'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/examples/build_system/cmake/import_lib/main/lib/tinyxml2'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/examples/peripherals/secure_element/atecc608_ecdsa/components/esp-cryptoauthlib'...
Submodule path 'components/asio/asio': checked out 'f31694c9f1746ba189a4bcae2e34db15135ddb22'
Submodule path 'components/bootloader/subproject/components/micro-ecc/micro-ecc': checked out 'd037ec89546fad14b5c4d5456c2e23a71e554966'
Submodule path 'components/bt/controller/lib_esp32': checked out 'ec4b716eb60c50f14642f7b7ce9825791469e4c1'
Submodule path 'components/bt/controller/lib_esp32c3_family': checked out 'a01066d87297c330196162fd84cdb108cfa9f67b'
Submodule path 'components/bt/host/nimble/nimble': checked out '554cd264cd028886411b183885bb21b47b8901a6'
Submodule path 'components/cbor/tinycbor': checked out '085ca40781f7c39febe6d14fb7e5cba342e1804b'
Submodule path 'components/cmock/CMock': checked out 'eeecc49ce8af123cf8ad40efdb9673e37b56230f'
Submodule 'vendor/c_exception' (https://github.com/throwtheswitch/cexception.git) registered for path 'components/cmock/CMock/vendor/c_exception'
Submodule 'vendor/unity' (https://github.com/throwtheswitch/unity.git) registered for path 'components/cmock/CMock/vendor/unity'
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/cmock/CMock/vendor/c_exception'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/cmock/CMock/vendor/unity'...
Submodule path 'components/cmock/CMock/vendor/c_exception': checked out '71b47be7c950f1bf5f7e5303779fa99a16224bb6'
Submodule path 'components/cmock/CMock/vendor/unity': checked out 'cf949f45ca6d172a177b00da21310607b97bc7a7'
Submodule path 'components/coap/libcoap': checked out '98954eb30a2e728e172a6cd29430ae5bc999b585'
Submodule 'ext/tinydtls' (https://github.com/eclipse/tinydtls.git) registered for path 'components/coap/libcoap/ext/tinydtls'
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/coap/libcoap/ext/tinydtls'...
Submodule path 'components/coap/libcoap/ext/tinydtls': checked out '7f8c86e501e690301630029fa9bae22424adf618'
Submodule path 'components/esp_wifi/lib': checked out '349ac708040fcd6ce3142a4413d501c2d27af24c'
Submodule path 'components/esptool_py/esptool': checked out '5c742218233098934300abe5b9c3d357a7d139cb'
Submodule path 'components/expat/expat': checked out 'a28238bdeebc087071777001245df1876a11f5ee'
Submodule path 'components/json/cJSON': checked out 'd348621ca93571343a56862df7de4ff3bc9b5667'
Submodule path 'components/libsodium/libsodium': checked out '4f5e89fa84ce1d178a6765b8b46f2b6f91216677'
Submodule path 'components/lwip/lwip': checked out '2195f7416fb3136831babf3e96c027a73075bd4f'
Submodule path 'components/mbedtls/mbedtls': checked out 'dc406b82b20481bde74a60fa8a776285d3fb9cf3'
Submodule path 'components/mqtt/esp-mqtt': checked out '89894bd0c611b1392967fe90bb49682eba858383'
Submodule path 'components/nghttp/nghttp2': checked out '8f7b008b158e12de0e58247afd170f127dbb6456'
Submodule 'third-party/mruby' (https://github.com/mruby/mruby) registered for path 'components/nghttp/nghttp2/third-party/mruby'
Submodule 'third-party/neverbleed' (https://github.com/tatsuhiro-t/neverbleed.git) registered for path 'components/nghttp/nghttp2/third-party/neverbleed'
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/nghttp/nghttp2/third-party/mruby'...
Cloning into 'C:/Users/Francesco/esp/esp-at/esp-idf/components/nghttp/nghttp2/third-party/neverbleed'...
Submodule path 'components/nghttp/nghttp2/third-party/mruby': checked out '7c91efc1ffda769a5f1a872c646c82b00698f1b8'
Submodule path 'components/nghttp/nghttp2/third-party/neverbleed': checked out 'b967ca054f48a36f82d8fcdd32e54ec5144f2751'
Submodule path 'components/protobuf-c/protobuf-c': checked out 'dac1a65feac4ad72f612aab99f487056fbcf5c1a'
Submodule path 'components/spiffs/spiffs': checked out 'f5e26c4e933189593a71c6b82cda381a7b21e41c'
Submodule path 'components/tinyusb/tinyusb': checked out '334e95fac52a607150157ae5199a19e11f843982'
Submodule path 'components/unity/unity': checked out '7d2bf62b7e6afaf38153041a9d53c21aeeca9a25'
Submodule path 'examples/build_system/cmake/import_lib/main/lib/tinyxml2': checked out '7e8e249990ec491ec15990cf95b6d871a66cf64a'
Submodule path 'examples/peripherals/secure_element/atecc608_ecdsa/components/esp-cryptoauthlib': checked out 'bb672b0437485fc7420add178299631692b15ac3'
Update completed
WARNING: IDF_PATH environment variable is set to c:\espressif\frameworks\esp-idf-v4.4 but idf.py path indicates IDF directory c:\users\francesco\esp\esp-at\esp-idf. Using the environment variable directory, but results may be unexpected...
Traceback (most recent call last):
  File "esp-idf\tools\idf.py", line 812, in <module>
    main()
  File "esp-idf\tools\idf.py", line 728, in main
    cli = init_cli(verbose_output=checks_output)
  File "esp-idf\tools\idf.py", line 686, in init_cli
    extensions.append((name, import_module(name)))
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\espressif\frameworks\esp-idf-v4.4\tools\idf_py_actions\core_ext.py", line 13, in <module>
    from idf_py_actions.constants import GENERATORS, PREVIEW_TARGETS, SUPPORTED_TARGETS, URL_TO_DOC
ImportError: cannot import name 'URL_TO_DOC' from 'idf_py_actions.constants' (C:\Users\Francesco\esp\esp-at\esp-idf\tools\idf_py_actions\constants.py)
idf.py build ret: 1
idf.py build failed

**Comment by FBEZ** [comment]
Any idea about what can cause this issue?

**Comment by xcguang** [comment]
You can try:
1. unset IDF_PATH
or 
2. set IDF_PATH=c:\users\francesco\esp\esp-at\esp-idf

**Comment by ustccw** [comment]
May I know if there is any update? If the issue still exists, please let us know.

**Comment by ustccw** [comment]
Closing due to inactivity. Please feel free to re-open or file a new issue if you have any more questions.
