### ISSUE TITLE
esp-at编译配置失败

### ISSUE THREAD

**Issue by MrYanLK** [espressif/esp-at#721]
您好，esp-idf已能正常编译项目，esp-at/esp-idf下也正常执行了./install 和 . ./export.sh ，但是我在esp-at目录下执行./build.py menuconfig时报错如下

root@DESKTOP-6TBOMGV:/home/ylk/esp-at# ./build.py menuconfig
Platform name:ESP32     Module name:WROOM-32    Silence:0
submodules check completed for updates.
softap_pmk.patch does not need to be applied
patches check completed for updates.
Ready to set up environment variables..
PATH is /home/ylk/esp-at/esp-idf/components/esptool_py/esptool:/home/ylk/esp-at/esp-idf/components/espcoredump:/home/ylk/esp-at/esp-idf/components/partition_table:/home/ylk/esp-at/esp-idf/components/app_update:/home/ylk/esp-at/esp-idf/components/esptool_py/esptool:/home/ylk/esp-at/esp-idf/components/espcoredump:/home/ylk/esp-at/esp-idf/components/partition_table:/home/ylk/esp-at/esp-idf/components/app_update:/root/.espressif/tools/xtensa-esp-elf-gdb/11.2_20220823/xtensa-esp-elf-gdb/bin:/root/.espressif/tools/riscv32-esp-elf-gdb/11.2_20220823/riscv32-esp-elf-gdb/bin:/root/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin:/root/.espressif/tools/xtensa-esp32s2-elf/esp-2022r1-11.2.0/xtensa-esp32s2-elf/bin:/root/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin:/root/.espressif/tools/riscv32-esp-elf/esp-2022r1-11.2.0/riscv32-esp-elf/bin:/root/.espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin:/root/.espressif/tools/openocd-esp32/v0.11.0-esp32-20221026/openocd-esp32/bin:/root/.espressif/python_env/idf5.0_py3.10_env/bin:/home/ylk/esp-at/esp-idf/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
IDF_PYTHON_ENV_PATH is /root/.espressif/python_env/idf5.0_py3.10_env
sys.platform is linux
export str is
PATH is /home/ylk/esp-at/esp-idf/components/esptool_py/esptool:/home/ylk/esp-at/esp-idf/components/espcoredump:/home/ylk/esp-at/esp-idf/components/partition_table:/home/ylk/esp-at/esp-idf/components/app_update:/home/ylk/esp-at/esp-idf/components/esptool_py/esptool:/home/ylk/esp-at/esp-idf/components/espcoredump:/home/ylk/esp-at/esp-idf/components/partition_table:/home/ylk/esp-at/esp-idf/components/app_update:/root/.espressif/tools/xtensa-esp-elf-gdb/11.2_20220823/xtensa-esp-elf-gdb/bin:/root/.espressif/tools/riscv32-esp-elf-gdb/11.2_20220823/riscv32-esp-elf-gdb/bin:/root/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin:/root/.espressif/tools/xtensa-esp32s2-elf/esp-2022r1-11.2.0/xtensa-esp32s2-elf/bin:/root/.espressif/tools/xtensa-esp32s3-elf/esp-2022r1-11.2.0/xtensa-esp32s3-elf/bin:/root/.espressif/tools/riscv32-esp-elf/esp-2022r1-11.2.0/riscv32-esp-elf/bin:/root/.espressif/tools/esp32ulp-elf/2.35_20220830/esp32ulp-elf/bin:/root/.espressif/tools/openocd-esp32/v0.11.0-esp32-20221026/openocd-esp32/bin:/root/.espressif/python_env/idf5.0_py3.10_env/bin:/home/ylk/esp-at/esp-idf/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
IDF_PYTHON_ENV_PATH is /root/.espressif/python_env/idf5.0_py3.10_env
Executing action: menuconfig
Running cmake in directory /home/ylk/esp-at/build
Executing "cmake -G Ninja -DPYTHON_DEPS_CHECKED=1 -DESP_PLATFORM=1 -DIDF_TARGET=esp32 -DCCACHE_ENABLE=0 /home/ylk/esp-at"...
silence:0 sdkconfig:/home/ylk/esp-at/module_config/module_esp32_default/sdkconfig.defaults
esp-at branch: master
esp-at docs version: latest
-- Found Git: /usr/bin/git (found version "2.34.1")
CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule
  components/bootloader/subproject/components/micro-ecc/micro-ecc is out of
  date.  Run 'git submodule update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/bt/controller/lib_esp32 is out of date.  Run 'git
  submodule update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/bt/controller/lib_esp32c2/esp32c2-bt-lib is out of
  date.  Run 'git submodule update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/bt/controller/lib_esp32c3_family is out of date.
  Run 'git submodule update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/bt/controller/lib_esp32h2/esp32h2-bt-lib is out of
  date.  Run 'git submodule update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/bt/host/nimble/nimble is out of date.  Run 'git
  submodule update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/cmock/CMock is out of date.  Run 'git submodule
  update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/esp_phy/lib is out of date.  Run 'git submodule
  update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/esp_wifi/lib is out of date.  Run 'git submodule
  update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/ieee802154/lib is out of date.  Run 'git submodule
  update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/json/cJSON is out of date.  Run 'git submodule
  update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/lwip/lwip is out of date.  Run 'git submodule
  update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/mbedtls/mbedtls is out of date.  Run 'git
  submodule update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/mqtt/esp-mqtt is out of date.  Run 'git submodule
  update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/openthread/lib is out of date.  Run 'git submodule
  update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/openthread/openthread is out of date.  Run 'git
  submodule update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

CMake Warning at esp-idf/tools/cmake/git_submodules.cmake:52 (message):
  Git submodule components/protobuf-c/protobuf-c is out of date.  Run 'git
  submodule update --init --recursive' to fix.
Call Stack (most recent call first):
  esp-idf/tools/cmake/build.cmake:77 (git_submodule_check)
  esp-idf/tools/cmake/build.cmake:219 (__build_get_idf_git_revision)
  esp-idf/tools/cmake/idf.cmake:53 (__build_init)
  esp-idf/tools/cmake/project.cmake:12 (include)
  CMakeLists.txt:89 (include)

-- Component directory /home/ylk/esp-at/components/fs_image does not contain a CMakeLists.txt file. No component will be added
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- The ASM compiler identification is GNU
-- Found assembler: /root/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /root/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /root/.espressif/tools/xtensa-esp32-elf/esp-2022r1-11.2.0/xtensa-esp32-elf/bin/xtensa-esp32-elf-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Building ESP-IDF components for target esp32
Solving dependencies requirements
CMake Error at esp-idf/tools/cmake/build.cmake:519 (message):
  Traceback (most recent call last):

    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/prepare_components/__main__.py", line 6, in <module>
      main()
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/prepare_components/prepare.py", line 124, in main
      args.func(args)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/prepare_components/prepare.py", line 27, in prepare_dep_dirs
      ComponentManager(
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/core.py", line 62, in wrapper
      return func(self, *args, **kwargs)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/core.py", line 438, in prepare_dep_dirs
      downloaded_component_paths, downloaded_component_version_dict = download_project_dependencies(
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/dependencies.py", line 111, in download_project_dependencies
      solution = solver.solve()
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/version_solver/version_solver.py", line 34, in solve
      self.solve_manifest(manifest)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/version_solver/version_solver.py", line 53, in solve_manifest
      self.solve_component(requirement)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_manager/version_solver/version_solver.py", line 56, in solve_component
      cmp_with_versions = requirement.source.versions(
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_tools/sources/web_service.py", line 143, in versions
      cmp_with_versions = self.api_client.versions(component_name=name, spec=spec)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_tools/api_client.py", line 285, in wrapper
      return f(self, request=request, *args, **kwargs)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_tools/api_client.py", line 305, in versions
      body = request(
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_tools/api_client.py", line 282, in request
      return self._base_request(
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/idf_component_tools/api_client.py", line 213, in _base_request
      response = session.request(
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
      resp = self.send(prep, **send_kwargs)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/requests/sessions.py", line 745, in send
      r.content
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/requests/models.py", line 899, in content
      self._content = b"".join(self.iter_content(CONTENT_CHUNK_SIZE)) or b""
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/requests/models.py", line 816, in generate
      yield from self.raw.stream(chunk_size, decode_content=True)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/response.py", line 935, in stream
      data = self.read(amt=amt, decode_content=decode_content)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/response.py", line 874, in read
      data = self._raw_read(amt)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/response.py", line 809, in _raw_read
      data = self._fp_read(amt) if not fp_closed else b""
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/urllib3/response.py", line 794, in _fp_read
      return self._fp.read(amt) if amt is not None else self._fp.read()
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/cachecontrol/filewrapper.py", line 96, in read
      self._close()
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/cachecontrol/filewrapper.py", line 76, in _close
      self.__callback(result)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/cachecontrol/controller.py", line 353, in cache_response
      self._cache_set(cache_url, request, response, body, expires_time)
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/cachecontrol/controller.py", line 274, in _cache_set
      self.serializer.dumps(request, response, body),
    File "/root/.espressif/python_env/idf5.0_py3.10_env/lib/python3.10/site-packages/cachecontrol/serialize.py", line 54, in dumps
      u"strict": response.strict,

  AttributeError: 'HTTPResponse' object has no attribute 'strict'

Call Stack (most recent call first):
  esp-idf/tools/cmake/project.cmake:440 (idf_build_process)
  CMakeLists.txt:91 (project)

-- Configuring incomplete, errors occurred!
See also "/home/ylk/esp-at/build/CMakeFiles/CMakeOutput.log".
cmake failed with exit code 1
A fatal error occurred: idf.py build failed
root@DESKTOP-6TBOMGV:/home/ylk/esp-at#

**Comment by xcguang** [comment]
python -m pip install urllib3==1.26.0 试试

**Comment by MrYanLK** [comment]
好像可以了，感谢！
